area:backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**/*'

area:frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*'

area:ci-cd:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'

area:documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

area:infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose.yml'
          - 'Dockerfile'
          - 'frontend/Dockerfile'
