"""Turning a turn's real executed steps into a runnable script or notebook.

Shared by the always-on per-turn artifact (`orchestrator._write_script`) and
the on-demand export route (`routes/export.py`), so both agree on what "what
actually ran" means -- steps pulled straight from the investigation, never
reconstructed from the model's description of what it did. That is the same
grounding rule `check_grounding` applies to an answer, applied here to code.

Two loader shapes, not one, because the two callers ship to different places:
the always-on artifact stays inside the session workspace, next to the
per-table Feather files `Session._materialize` already wrote there, so it
reads those in place. The on-demand export leaves the workspace -- it is
downloaded and may be opened on a machine with no Wizard session at all -- so
it ships its own CSV copies (`bundle_files`) and reads those instead.

A connector-sourced table is never embedded either way. It is looked up by
name at run time through `ConnectionStore.by_name`, which exists for exactly
this: the script names the connection, never a credential.
"""

from __future__ import annotations

from typing import Any

from src.config import settings
from src.core.session import Session


HEADER_IMPORTS = [
    "import matplotlib.pyplot as plt",
    "import numpy as np",
    "import pandas as pd",
    "import seaborn as sns",
]

CONNECTOR_IMPORTS = [
    "from src.core.connectors.registry import build as build_connector",
    "from src.core.connectors.store import connection_store",
]


def dataset_loader_lines(session: Session, *, file_template: str, reader: str) -> tuple[list[str], bool]:
    """Lines that rebuild ``tables`` (and ``df``) the way generated code expects.

    ``file_template`` takes one ``{key}`` placeholder -- e.g. ``"tables/{key}.feather"``
    for the in-workspace artifact, ``"data/{key}.csv"`` for a downloaded bundle.
    ``reader`` is the matching pandas call, e.g. ``"pd.read_feather"``.

    Returns the lines plus whether a connector-sourced table was involved, so
    the caller only adds the connector imports when something needs them.
    """
    lines: list[str] = ["tables = {}"]
    needs_connector = False
    for handle in session.datasets.values():
        key = handle.table_key
        if handle.origin:
            needs_connector = True
            target = handle.profile.get("target", key)
            lines.append(f"# '{handle.name}' is read from the connection '{handle.origin}', looked up by name")
            lines.append("# at run time -- this script never carries a credential.")
            lines.append(f"_spec = connection_store.by_name({handle.origin!r})")
            lines.append("if _spec is None:")
            lines.append(f'    raise RuntimeError("No saved connection named {handle.origin!r} on this machine.")')
            lines.append("_conn = build_connector(_spec, connection_store.secret_for(_spec))")
            lines.append(f"tables[{key!r}] = _conn.sample({target!r}, limit={settings.CONNECTOR_MAX_ROWS})")
            lines.append("_conn.close()")
        else:
            path = file_template.format(key=key)
            lines.append(f'tables[{key!r}] = {reader}("{path}")')
        lines.append("")

    active = session.active_handle
    if active is None and session.datasets:
        active = next(iter(session.datasets.values()))
    if active is not None:
        lines.append(f"df = tables[{active.table_key!r}]")
    return lines, needs_connector


def build_script(instruction: str, steps: list[dict[str, str]], session: Session, *, bundle: bool = False) -> str:
    """Assembles the runnable ``.py`` from the steps that actually executed.

    ``bundle=True`` targets a downloaded zip (CSV copies ship alongside);
    ``bundle=False`` targets the in-workspace artifact (reads the Feather
    files already sitting next to it).
    """
    if not steps:
        return ""

    loader_lines, needs_connector = dataset_loader_lines(
        session,
        file_template="data/{key}.csv" if bundle else "tables/{key}.feather",
        reader="pd.read_csv" if bundle else "pd.read_feather",
    )

    header = [
        '"""Analysis generated by Wizard.',
        "",
        f"Question: {instruction}",
        "",
        (
            "Run this from inside the extracted bundle -- the data/ folder ships alongside it."
            if bundle
            else "Run this from inside the session workspace -- tables/ already holds this analysis's data."
        ),
        '"""',
        "",
        *HEADER_IMPORTS,
        *(CONNECTOR_IMPORTS if needs_connector else []),
        "",
        *loader_lines,
        "",
    ]

    body: list[str] = []
    for index, step in enumerate(steps, start=1):
        body.append(f"# --- Step {index}: {step.get('goal') or 'analysis'} " + "-" * 20)
        body.append(step["code"])
        body.append("")

    return "\n".join(header + body)


def build_notebook(
    instruction: str, steps: list[dict[str, str]], session: Session, *, bundle: bool = False
) -> dict[str, Any]:
    """The same content as `build_script`, split into nbformat-4 cells.

    Built by hand rather than through the `nbformat` package -- this is a
    plain JSON shape, not worth a new dependency for.
    """
    if not steps:
        return {}

    loader_lines, needs_connector = dataset_loader_lines(
        session,
        file_template="data/{key}.csv" if bundle else "tables/{key}.feather",
        reader="pd.read_csv" if bundle else "pd.read_feather",
    )

    intro = [
        "# Analysis generated by Wizard",
        "",
        f"**Question:** {instruction}",
        "",
        (
            "Run this from inside the extracted bundle -- the `data/` folder ships alongside it."
            if bundle
            else "Run this from inside the session workspace -- `tables/` already holds this analysis's data."
        ),
    ]
    import_lines = [*HEADER_IMPORTS, *(CONNECTOR_IMPORTS if needs_connector else []), "", *loader_lines]

    cells = [_markdown_cell(intro), _code_cell(import_lines)]
    for index, step in enumerate(steps, start=1):
        cells.append(_markdown_cell([f"### Step {index}: {step.get('goal') or 'analysis'}"]))
        cells.append(_code_cell(step["code"].splitlines()))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def bundle_files(session: Session) -> dict[str, bytes]:
    """CSV bytes for every file-based table, keyed by the path the loader reads.

    Empty when every table in the session came from a connection -- nothing to
    bundle, since a connector-sourced table is never embedded.
    """
    files: dict[str, bytes] = {}
    for handle in session.datasets.values():
        if handle.origin:
            continue
        files[f"data/{handle.table_key}.csv"] = handle.df.to_csv(index=False).encode("utf-8")
    return files


def _code_cell(lines: list[str]) -> dict[str, Any]:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": _source(lines)}


def _markdown_cell(lines: list[str]) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": _source(lines)}


def _source(lines: list[str]) -> list[str]:
    """nbformat's line-list convention: every line but the last keeps its newline."""
    if not lines:
        return []
    return [f"{line}\n" for line in lines[:-1]] + [lines[-1]]


__all__ = ["build_notebook", "build_script", "bundle_files", "dataset_loader_lines"]
