"use client";

import { motion } from "framer-motion";
import { BarChart, LineChart, PieChart } from "lucide-react";

export default function Visualizer({ imageData }) {
    if (!imageData) {
        return (
            <div className="h-[600px] glass-panel rounded-2xl flex flex-col items-center justify-center text-slate-500 border-dashed border-2 border-white/5 bg-slate-950/30">
                <div className="flex gap-4 mb-4 opacity-50">
                    <BarChart className="w-8 h-8" />
                    <LineChart className="w-8 h-8" />
                    <PieChart className="w-8 h-8" />
                </div>
                <p className="font-mono text-sm">NO_VISUALIZATION_DATA</p>
                <p className="text-xs opacity-50 max-w-xs text-center mt-2">Charts generated by the agent will appear here automatically.</p>
            </div>
        );
    }

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="h-[600px] glass-panel rounded-2xl p-2 relative group overflow-hidden"
        >
            <div className="absolute inset-0 bg-gradient-to-tr from-indigo-500/5 to-purple-500/5 pointer-events-none" />

            <div className="h-full w-full rounded-xl overflow-hidden bg-white/5 backdrop-blur-sm flex items-center justify-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                    src={`data:image/png;base64,${imageData}`}
                    alt="Data Visualization"
                    className="max-h-full max-w-full object-contain shadow-2xl"
                />
            </div>

            <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <button className="px-3 py-1 bg-black/50 text-white text-xs rounded-full backdrop-blur-md border border-white/10 hover:bg-white/10">
                    Download
                </button>
                <button className="px-3 py-1 bg-black/50 text-white text-xs rounded-full backdrop-blur-md border border-white/10 hover:bg-white/10">
                    Expand
                </button>
            </div>
        </motion.div>
    );
}
