import pytest
from fastapi.testclient import TestClient
import pandas as pd
import io
import sys
import os
from unittest.mock import patch

# Ensure backend can import its modules
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.api.api import app

client = TestClient(app)


@pytest.fixture
def sample_csv():
    df = pd.DataFrame(
        {
            "bedrooms": [3, 4, 2, 5, 3],
            "price": [300000, 450000, 200000, 600000, 320000],
            "month": ["May", "May", "June", "May", "July"],
            "owner": ["Alice", "Bob", "Charlie", "Alice", "Eve"],
        }
    )
    csv_file = io.StringIO()
    df.to_csv(csv_file, index=False)

    # Convert to bytes for upload
    csv_bytes = io.BytesIO(csv_file.getvalue().encode("utf-8"))
    return csv_bytes


def test_upload_and_chat_flow(sample_csv):
    """
    Simulates the user journey:
    1. Upload dataset -> Get basic info (summary)
    2. Chat -> "show profit... in may" -> Get plotting code/output
    """

    # 1. Upload
    files = {"file": ("backend/dataset/housing.csv", sample_csv, "text/csv")}
    response = client.post("/upload", files=files)

    assert response.status_code == 200, f"Upload failed: {response.text}"
    data = response.json()

    # Verify "basic info"
    assert data["message"] == "Dataset loaded successfully"
    assert data["filename"] == "backend/dataset/housing.csv"
    assert data["shape"] == [5, 4]  # 5 rows, 4 cols
    assert "summary" in data
    assert "Dataset Overview" in data["summary"]
    assert "Statistical Summary" in data["summary"]

    # 2. Chat
    # Mock the LLM execution to avoid live model dependency
    # We patch the agent instance's run method

    with patch("src.core.agent.flow.ScientificAgent.run") as mock_run:
        mock_run.return_value = (
            "Plot generated.",
            "df['price'].plot()",
            "base64image...",
        )

        chat_payload = {
            "message": "show the profit generated by house owner in the month of may using plot"
        }
        chat_response = client.post("/chat", json=chat_payload)

        assert chat_response.status_code == 200
        chat_data = chat_response.json()

        # Verify output
        assert chat_data["response"] == "Plot generated."
        assert chat_data["code"] == "df['price'].plot()"
        assert chat_data["image"] == "base64image..."

        # Verify agent was called with correct context (implied by state["df"] being passed)
        # Note: We can't easily check the arg value here without complex mock assertions,
        # but the fact it didn't error means state["df"] was present.


def test_chat_without_upload():
    # Reset app state (FastAPI app state persists in memory for the process somewhat,
    # but TestClient usually isolates per request if handled right,
    # BUT our 'state' dict is global in api.py module scope).
    # We need to manually reset logic if we want to test "no upload"
    # OR rely on import reloading, which is hard.
    # Alternatives:
    # 1. We just ran a test that uploaded. The state is dirty.
    # 2. Explicitly clear state in this test logic via some hack or endpoint?
    # Better: just clear the state dict directly.

    from src.api.api import state

    state["df"] = None

    response = client.post("/chat", json={"message": "What is the mean of A?"})
    assert response.status_code == 412
    assert response.json()["detail"] == "No dataset loaded."
