name: Bundle Size Check

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '20'
      - name: Install and Build
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Report Bundle Size
        uses: preactjs/compressed-size-action@f322c295dde06a1cb7ccaef105732dd8a726d1d9  # v2
        with:
          pattern: "{frontend/.next/static/**/*.js,frontend/public/**/*.js}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "build"
          cwd: "frontend"
