name: License Check

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - name: Check License Compliance
        uses: Telefonica/check-license-compliance@318472864438e7a2150027a5c47212d1901accb3  # v2
